### ISSUE TITLE
Missing egdsimulator folder with __init__.py

### ISSUE THREAD

**Issue by kldjaff** [nubisware/egdsimulator#1]
After clone the code and run 
```
$ python setup.py install
```
It shows the error with 
```
running install
running bdist_egg
running egg_info
writing EGDSimulator.egg-info/PKG-INFO
writing top-level names to EGDSimulator.egg-info/top_level.txt
writing dependency_links to EGDSimulator.egg-info/dependency_links.txt
error: package directory 'egdsimulator' does not exist
```
You have to manually create the folder named `egdsimulator` and create an empty `__init__.py` inside.
And then, you could install the package.

Please add the folder and the `__init__.py` in the main trunk

**Comment by dcore94** [comment]
Should be closed with release #0.5
