### ISSUE TITLE
Not an issue with the project...

### ISSUE THREAD

**Issue by EverestSoftwareLLC** [nubisware/egdsimulator#2]
Hello,

>Please refer to this document for further information.

The link to the PDF has changed/does not work. Do you have a copy of the PDF or another link?

Thanks,

Mark

**Comment by EverestSoftwareLLC** [comment]
I found the PDF. I was seeking the EGD protocol specification and that PDF is not it. Anyone have the specification?

**Comment by dcore94** [comment]
Hi Mark. I am very sorry but that's the only useful resource we found at that time. GE doesn't seam to have much interest in this protocol or at least  in supporting external devs.
Btw can you somehow point us to the new pdf so that we can fix the docs? Thank you very much, Marco.

**Comment by EverestSoftwareLLC** [comment]
Thanks for the response.

I found it at the internet archive, using the URL and once at the site, clicking around the snapshots until one worked.
